### ISSUE TITLE
Problema Cota Superior

### ISSUE THREAD

**Issue by mgutierrezc** [verduralegorica/meds_segundo#11]
Deben decirle al participante en la pregunta cuál es su dotación de dinero para responder. Sino, pensará que puede colocar cualquier cantidad y solo se dará cuenta al equivocarse

![error cota superior](https://user-images.githubusercontent.com/43623521/93974553-956bf700-fd3b-11ea-9a2f-fefe8a56502e.png)

**Comment by DanielaVLl** [comment]
Hola Marco
Estábamos pensando que si colocamos que máximo puede colocar 50, esto puede inducir a los participantes a colocar un número más alto, por eso no lo estábamos especificando. Ya si es que ponen un número muy alto (así como 1000), se darían cuanta del error, ¿no sé qué te parece esto?

**Comment by mgutierrezc** [comment]
Mmmm, sí puede haber anclaje, pero siento que esa pregunta necesita un mayor contexto. Por ahora, lo podemos dejar como está. Sería bueno que consultaran sobre esta a su asesor sobre esta preg en el futuro
